name: Org Repo Metrics Report

on:
  pull_request:
    types: [synchronize]
  workflow_dispatch:
    inputs:
      fromdate: 2023-11-01
      todate: 2023-12-18

jobs:
  org-repo-metrics-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get organization repository metrics
        uses: nicklegan/github-org-repo-metrics-action@v2.0.1
        with:
          token: ${{ secrets.ORG_TOKEN }}
          fromdate: ${{ github.event.inputs.fromdate }} # Used for workflow dispatch input
          todate: ${{ github.event.inputs.todate }} # Used for workflow dispatch input
          org: 'KUNLE BALO'
          days: '30'
          stale: '35'
          old: '120'
        # sort: 'openedPullRequests'
        # sort-order: 'desc'
        # json: 'false'
        # diff-report: 'false'
        # appid: ${{ secrets.APPID }}
        # privatekey: ${{ secrets.PRIVATEKEY }}
        # installationid: ${{ secrets.INSTALLATIONID }}
